#! /usr/local/bin/ruby

require_relative 'Lexer.rb'
require_relative 'Parser.rb'
require_relative 'Ast_check_table.rb'
require_relative 'Ast_Run.rb'
require_relative 'BaseFunk.rb'

def main
	ARGV[0] =~ /\w+\.rtn/
	if $&.nil?; puts "Extensión desconocida"; return; end
	begin
		input = File::read(ARGV[0])
	rescue
		puts "Archivo no encontrado"
		return
	end
	lexer = Lexer.new(input)						#Crea un objeto Lexer con el archivo de entrada
	parser = Parser.new								#Crea un nuevo objeto Parser
	
	lexer.capturador								#Captura Tokens
	
	if lexer.enviarCaptura.nil? == false
		ast = parser.parse(lexer.enviarCaptura)		#Parsea Captura
		if ast.nil? == false
			ast.fill_table							#Llenar Tabla Sintáctica
			if $lista_errores_sintacticos.size == 0
				#$tabla_de_tablas.print_symtab		#Imprimir Tabla de Sintaxis, en caso de que se quiera
				ast.run_inst						#Correr Retina
				$retina.toFile(ARGV[0][0..-5])		#Crear Imagen
			else
				puts $lista_errores_sintacticos[0]	#Imprimir Errores Sintacticos
			end
		end
	end
end

main
